### PR TITLE
Fix text search of features does not handle spaces in attribute values

### LINKED ISSUE #262: Text search of features does not handle spaces in attribute values
Given this gff file:

```
##gff-version 3
ctgA	example	gene	1050	9000	.	+	.	ID=EDEN
ctgA	est	EST_match	1150	7200	.	+	.	ID=Match1;Target=agt 1
ctgA	est	EST_match	5410	7503	.	-	.	ID=Match2;Target=agt 1
ctgA	est	EST_match	7500	8000	.	-	.	ID=Match3;Target=agt A
ctgA	est	EST_match	8000	9000	.	-	.	ID=Match4;Target=agt B
ctgA	est	EST_match	9500	9900	.	-	.	ID=Match5;Target=agt_1
##FASTA
>ctgA
cattgttgcggagttgaacaACGGCATTAGGAACACTTCCGTCTCtcacttttatacgat
tatgattggttctttagccttggtttagattggtagtagtagcggcgctaatgctacctg
etc...
```

it seems that spaces in attribute values cause problems to the search feature functionality. E.g., search for `.1` gives:

image

Search for `EDEN.1` ("EDEN" only is ok):

image

Search `.A` does not give hits (ok) but `.B` gives:

image

### PR DESCRIPTION
**Pull request by shashankbrgowda**
Enclosing search term in quotes seems to fix the issue. 

Fixes #262

### CODE REVIEW

**Comment by dariober** [comment]
@shashankbrgowda Thanks for looking into this! In `packages/apollo-collaboration-server/src/features/features.service.ts` I replaced:

```
.find({ $text: { $search: term }, refSeq: refSeqs })
```

with:

```
.find({ $text: { $search: `"${term}"` }, refSeq: refSeqs })
```

and things seem to work as expected, even when the gff value contains double-quotes. However, searching for `"agt 1"` (quotes included) now returns four hits instead of two.

image

**Comment by shashankbrgowda** [comment]
@dariober Sorry I had to create another draft PR for this Issue. 

I think Its matching text like this "Target=agt830.5 1 654" in the attributes column when we type "agt 1" (quotes included) in search bar and it looks like its not a random match. We can remove quotes at the start and end of the search term If we don't want matches like this.

**Comment by dariober** [comment]
I'd be interested to understand how the search is done... Here's another odd case. I edited the test file `space.gff3` to have Match5 feature to be:

```
ctgA	est	EST_match	9520	9900	.	-	.	ID=Match5;Target=agt_1;Note=mRNA with both CDSs and UTRs and 7-transmembrane and someKeyWord
```

In these tests, the second argument is the number of expected matches. The tests succeed, even the last 4 should fail:

```
cy.searchFeatures('transmem', 0)
cy.searchFeatures('transmembrane', 1)
cy.searchFeatures('7-transmembrane', 1)
cy.searchFeatures('someKeyWord', 1)
cy.searchFeatures('mRNA', 1)
cy.searchFeatures('UTRs', 1)
cy.searchFeatures('UTR', 1) // Why one match? Should be zero
cy.searchFeatures('with', 0) // Why zero matches?
cy.searchFeatures('both', 0) // Why zero matches?
cy.searchFeatures('and', 0) // Why zero matches?
```

**Comment by shashankbrgowda** [comment]
> I'd be interested to understand how the search is done... Here's another odd case. I edited the test file `space.gff3` to have Match5 feature to be:
> 
> ```
> ctgA	est	EST_match	9520	9900	.	-	.	ID=Match5;Target=agt_1;Note=mRNA with both CDSs and UTRs and 7-transmembrane and someKeyWord
> ```
> 
> In these tests, the second argument is the number of expected matches. The tests succeed, even the last 4 should fail:
> 
> ```
> cy.searchFeatures('transmem', 0)
> cy.searchFeatures('transmembrane', 1)
> cy.searchFeatures('7-transmembrane', 1)
> cy.searchFeatures('someKeyWord', 1)
> cy.searchFeatures('mRNA', 1)
> cy.searchFeatures('UTRs', 1)
> cy.searchFeatures('UTR', 1) // Why one match? Should be zero
> cy.searchFeatures('with', 0) // Why zero matches?
> cy.searchFeatures('both', 0) // Why zero matches?
> cy.searchFeatures('and', 0) // Why zero matches?
> ```

I'm guessing "with" and "and" are stop words which will be filtered out, not sure about "both" might be a stop word too. We can set default_language to none If we want to parse each and every word.

**Pull request closed without merging**
