### PR TITLE
Make subfeatures selectable in gene glyphs

### PR DESCRIPTION
**Pull request by shashankbrgowda**
Fixes https://github.com/GMOD/Apollo3/issues/247

### CODE REVIEW

**Comment by shashankbrgowda** [comment]
@garrettjstevens PR is ready for review

example gff features used for testing
```
ctgA	example	gene	1050	9000	.	+	.	ID=EDEN;Name=EDEN;Note=protein kinase
ctgA	example	mRNA	1050	9000	.	+	.	ID=EDEN.1;Parent=EDEN;Name=EDEN.1;Note=Eden splice form 1;Index=1
ctgA	example	five_prime_UTR	1050	1200	.	+	.	Parent=EDEN.1
ctgA	example	CDS	1201	1500	.	+	0	Parent=EDEN.1
ctgA	example	CDS	3000	3902	.	+	0	Parent=EDEN.1
ctgA	example	CDS	5000	5500	.	+	0	Parent=EDEN.1
ctgA	example	CDS	7000	7608	.	+	0	Parent=EDEN.1
ctgA	example	three_prime_UTR	7609	9000	.	+	.	Parent=EDEN.1
ctgA	example	mRNA	1050	9000	.	+	.	ID=EDEN.2;Parent=EDEN;Name=EDEN.2;Note=Eden splice form 2;Index=1
ctgA	example	five_prime_UTR	1050	1200	.	+	.	Parent=EDEN.2
ctgA	example	CDS	1201	1500	.	+	0	Parent=EDEN.2
ctgA	example	CDS	5000	5500	.	+	0	Parent=EDEN.2
ctgA	example	CDS	7000	7608	.	+	0	Parent=EDEN.2
ctgA	example	three_prime_UTR	7609	9000	.	+	.	Parent=EDEN.2
ctgA	example	mRNA	1300	9000	.	+	.	ID=EDEN.3;Parent=EDEN;Name=EDEN.3;Note=Eden splice form 3;Index=1
ctgA	example	five_prime_UTR	1300	1500	.	+	.	Parent=EDEN.3
ctgA	example	five_prime_UTR	3000	3300	.	+	.	Parent=EDEN.3
ctgA	example	CDS	3301	3902	.	+	0	Parent=EDEN.3
ctgA	example	CDS	5000	5500	.	+	1	Parent=EDEN.3
ctgA	example	CDS	7000	7600	.	+	1	Parent=EDEN.3
ctgA	example	three_prime_UTR	7601	9000	.	+	.	Parent=EDEN.3
ctgA	example	gene	1000	9000	.	+	.	ID=gene00001;Name=EDEN
ctgA	example	mRNA	1050	9000	.	+	.	ID=mRNA00001;Parent=gene00001
ctgA	example	mRNA	1050	9000	.	+	.	ID=mRNA00002;Parent=gene00001
ctgA	example	mRNA	1300	9000	.	+	.	ID=mRNA00003;Parent=gene00001
ctgA	example	exon	1300	1500	.	+	.	Parent=mRNA00003
ctgA	example	exon	1050	1500	.	+	.	Parent=mRNA00001,mRNA00002
ctgA	example	exon	3000	3902	.	+	.	Parent=mRNA00001,mRNA00003
ctgA	example	exon	5000	5500	.	+	.	Parent=mRNA00001,mRNA00002,mRNA00003
ctgA	example	exon	7000	9000	.	+	.	Parent=mRNA00001,mRNA00002,mRNA00003
ctgA	example	CDS	1201	1500	.	+	0	ID=cds00001;Parent=mRNA00001
ctgA	example	CDS	3000	3902	.	+	0	ID=cds00001;Parent=mRNA00001
ctgA	example	CDS	5000	5500	.	+	0	ID=cds00001;Parent=mRNA00001
ctgA	example	CDS	7000	7600	.	+	0	ID=cds00001;Parent=mRNA00001
ctgA	example	CDS	1201	1500	.	+	0	ID=cds00002;Parent=mRNA00002
ctgA	example	CDS	5000	5500	.	+	0	ID=cds00002;Parent=mRNA00002
ctgA	example	CDS	7000	7600	.	+	0	ID=cds00002;Parent=mRNA00002
ctgA	example	CDS	3301	3902	.	+	0	ID=cds00003;Parent=mRNA00003
ctgA	example	CDS	5000	5500	.	+	1	ID=cds00003;Parent=mRNA00003
ctgA	example	CDS	7000	7600	.	+	1	ID=cds00003;Parent=mRNA00003
ctgA	example	CDS	3391	3902	.	+	0	ID=cds00004;Parent=mRNA00003
ctgA	example	CDS	5000	5500	.	+	1	ID=cds00004;Parent=mRNA00003
ctgA	example	CDS	7000	7600	.	+	1	ID=cds00004;Parent=mRNA00003
ctgA	ensembl_havana	gene	10000	18000	.	+	.	ID=gene:ENSG00000069998;Name=HDHD5;biotype=protein_coding;description=haloacid dehalogenase like hydrolase domain containing 5 [Source:HGNC Symbol%3BAcc:HGNC:1843];gene_id=ENSG00000069998;logic_name=ensembl_havana_gene_homo_sapiens;version=12
ctgA	ensembl_havana	mRNA	10000	18000	.	+	.	ID=transcript:ENST00000155674;Parent=gene:ENSG00000069998;Name=HDHD5-201;biotype=protein_coding;ccdsid=CCDS13741.1;tag=basic;transcript_id=ENST00000155674;transcript_support_level=1;version=9
ctgA	ensembl_havana	three_prime_UTR	10000	11000	.	+	.	Parent=transcript:ENST00000155674
ctgA	ensembl_havana	five_prime_UTR	11001	12000	.	+	.	Parent=transcript:ENST00000155674
ctgA	ensembl_havana	exon	12001	15000	.	+	.	Parent=transcript:ENST00000155674;Name=ENSE00001867638;constitutive=0;ensembl_end_phase=-1;ensembl_phase=2;exon_id=ENSE00001867638;rank=8;version=1
ctgA	ensembl_havana	CDS	17001	18000	.	+	1	ID=CDS:ENSP00000155674;Parent=transcript:ENST00000155674;protein_id=ENSP00000155674
```

**Comment by garrettjstevens** [comment]
Could you make it so the hover draws the shading over the area that will be selected when clicked?

For example, if you click on a CDS here:
image
then all of its locations are highlighted:
image

So when hovering over a CDS, it should shade just the three orange boxes and nothing else.

Also, could you make it so that clicking on an intron line selects the mRNA? (And that hovering over the intron line shades the whole mRNA)

**Comment by garrettjstevens** [comment]
Thanks, those changes are looking good. Looks like there's one more place the above mentioned chagne needs to be applied, where an exon is on multiple lines, the hover only highlights one line
image
where the selection is on both lines
image
The hover should show on both lines.

I also realized we need some visual indication that an mRNA or gene is selected. The gene can't be selected from the track, but it can from the table, so it needs some way to show that.

For mRNA, when it's selected, maybe we can do something that looks like the hover
image
but a bit darker.

We could then use the same shading for the gene, but over all rows in the gene instead of just one.

**Comment by shashankbrgowda** [comment]
> use the same shading for the gene, but over all rows in the gene instead of just one.

Highlighting exons on multiple rows on hover is not straight forward as hover is using mouse event and mousePosition to get row number. We need to make some changes to make it work, Shall I proceed ?

Other things seems to be working as you asked.

**Comment by garrettjstevens** [comment]
> We need to make some changes to make it work, Shall I proceed ?
Yes, feel free to make more extensive changes such as changing the base Glyph class, etc.

**Pull request merged**
